REQUETE_FICHIERS = 'fichiers'

EVENEMENT_CONSIGNATION_PRIMAIRE = 'consignationPrimaire'
EVENEMENT_FUUID_NOUVELLEVERSION = 'fuuidNouvelleVersion'
#EVENEMENT_REINDEXER_CONSIGNATION = 'reindexerConsignation'

EVENEMENT_JOB_IMAGE_DISPONIBLE = 'jobImageDisponible'
EVENEMENT_JOB_VIDEO_DISPONIBLE = 'jobVideoDisponible'
