PARAM_INSTANCE_ID = 'INSTANCE_ID'
ENV_WEB_PORT = 'WEB_PORT'
DOCKER_CONFIG_PKI_MILLEGRILLE = 'pki.millegrille'
CERTISSUER_PATH = 'CERTISSUER_PATH'

PARAM_DUREE_CERTIFICAT_JOURS = 'DUREE_JOURS'
PARAM_DUREE_CERTIFICAT_MINUTES = 'DUREE_MINUTES'
