REQUETE_FICHIERS = 'fichiers'

EVENEMENT_CONSIGNATION_PRIMAIRE = 'consignationPrimaire'
EVENEMENT_FUUID_NOUVELLEVERSION = 'fuuidNouvelleVersion'
COMMANDE_REINDEXER_CONSIGNATION = 'reindexerConsignation'
COMMANDE_SUPPRIMER_TUUIDS = 'supprimerTuuids'

ENV_FILEHOST_URL = 'FILEHOST_URL'
