ENV_DIR_STAGING = 'DIR_STAGING'
ENV_WEB_CERT_PEM = 'WEB_CERT_PEM'
ENV_WEB_KEY_PEM = 'WEB_KEY_PEM'
ENV_WEB_PORT = 'WEB_PORT'

DIR_DOWNLOAD = 'download'
DIR_DECHIFFRE = 'dechiffre'

DOMAINE_GROSFICHIERS = 'GrosFichiers'

# Timeouts en secondes
CONST_TIMEOUT_DECHIFFRE = 60 * 60 * 24
CONST_TIMEOUT_DOWNLOAD = 30

# FICHIER_BACKUP_COURANT = 'infoBackup.json'
#
# COMMANDE_DEMARRER_BACKUP = 'demarrerBackupTransactions'
# COMMANDE_RESET_BACKUP = 'resetBackup'
# COMMANDE_DECLENCHER_BACKUP = 'declencherBackup'
# COMMANDE_BACKUP_TRANSACTIONS = 'backupTransactions'
# COMMANDE_RESTAURER_TRANSACTIONS = 'restaurerTransactions'
# COMMANDE_CATALOGUE_TRAITE = 'catalogueTraite'
# COMMANDE_DOMAINE_TRAITE = 'domaineTraite'
#
# EVENEMENT_BACKUP_DEMARRAGE = 'demarrage'
# EVENEMENT_BACKUP_SUCCES = 'succes'
# EVENEMENT_BACKUP_ECHEC = 'echec'
# EVENEMENT_BACKUP_MISEAJOUR = 'maj'
# EVENEMENT_BACKUP_DOMAINE_MISEAJOUR = 'backupMaj'

EVENEMENT_GROSFICHIERS_CHANGEMENT_CONSIGNATION_PRIMAIRE = 'changementConsignationPrimaire'