PARAM_CERT_PATH = 'CERT_PEM'
PARAM_KEY_PATH = 'KEY_PEM'
PARAM_CA_PATH = 'CA_PATH'

ENV_WEB_PORT = 'WEB_PORT'

ENV_DIR_CONSIGNATION = 'DIR_CONSIGNATION'

DIR_ACTIFS = 'actifs'
DIR_ARCHIVES = 'archives'
DIR_ORPHELINS = 'orphelins'

DOMAINE_GROSFICHIERS = 'GrosFichiers'
DOMAINE_FICHIERS = 'fichiers'

EVENEMENT_PRESENCE = 'presence'
EVENEMENT_GROSFICHIERS_CHANGEMENT_CONSIGNATION_PRIMAIRE = 'changementConsignationPrimaire'

CONST_CHAMPS_CONFIG = ['type_store', 'url_download', 'consignation_url']
