services:
  media_images:
    image: "replace_me"
    user: "${CONTAINER_UID}:${CONTAINER_GID}"
    command: ["-m", "millegrilles_media", "--images"]
    x-millegrilles-certificat:
      roles:
        - media
      exchanges:
        - 2.prive
        - 1.public
    environment:
      - MQ_HOSTNAME=${MQ_HOSTNAME:-mq}
      - MQ_PORT=${MQ_PORT:-5673}
      - REDIS_HOSTNAME=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD_PATH=/run/secrets/passwd.redis.txt
      - KEY_PATH=/run/secrets/key_cert.pem
      - CA_PATH=/run/secrets/millegrille.pem
      - DIR_STAGING=/var/opt/millegrilles/staging/media
    volumes:
      - ${MILLEGRILLES_ROOT}/var/staging:/var/opt/millegrilles/staging
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 175M
      restart_policy:
        condition: any
        delay: 20s
    configs:
      - source: mgca
        target: /run/secrets/millegrille.pem
    secrets:
      - source: media
        target: key_cert.pem
      - source: passwd_redis
        target: passwd.redis.txt
    networks:
      - app_net
  media_video:
    image: "replace_me"
    user: "${CONTAINER_UID}:${CONTAINER_GID}"
    command: ["-m", "millegrilles_media", "--videos"]
    environment:
      - MQ_HOSTNAME=${MQ_HOSTNAME:-mq}
      - MQ_PORT=${MQ_PORT:-5673}
      - REDIS_HOSTNAME=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD_PATH=/run/secrets/passwd.redis.txt
      - KEY_PATH=/run/secrets/key_cert.pem
      - CA_PATH=/run/secrets/millegrille.pem
      - DIR_STAGING=/var/opt/millegrilles/staging/media
    volumes:
      - ${MILLEGRILLES_ROOT}/var/staging:/var/opt/millegrilles/staging
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 750M
      restart_policy:
        condition: any
        delay: 20s
    configs:
      - source: mgca
        target: /run/secrets/millegrille.pem
    secrets:
      - source: media
        target: key_cert.pem
      - source: passwd_redis
        target: passwd.redis.txt
    networks:
      - app_net

configs:
  mgca:
    file: ${MILLEGRILLES_ROOT}/etc/millegrille.pem

secrets:
  media:
    file: ${MILLEGRILLES_ROOT}/secrets/media_images.pem
  passwd_redis:
    file: ${MILLEGRILLES_ROOT}/secrets/redis.txt
