ENV_DIR_BACKUP = 'DIR_BACKUP'

COMMANDE_DEMARRER_BACKUP = 'demarrerBackupTransactions'
COMMANDE_RESET_BACKUP = 'resetBackup'
COMMANDE_DECLENCHER_BACKUP = 'declencherBackup'
COMMANDE_BACKUP_TRANSACTIONS = 'backupTransactions'
COMMANDE_RESTAURER_TRANSACTIONS = 'restaurerTransactions'

EVENEMENT_BACKUP_DEMARRAGE = 'demarrage'
EVENEMENT_BACKUP_SUCCES = 'succes'
EVENEMENT_BACKUP_ECHEC = 'echec'
EVENEMENT_BACKUP_MISEAJOUR = 'maj'
EVENEMENT_BACKUP_DOMAINE_MISEAJOUR = 'backupMaj'
