ENV_DIR_BACKUP = 'DIR_BACKUP'

COMMANDE_DEMARRER_BACKUP = 'demarrerBackupTransactions'

EVENEMENT_BACKUP_DEMARRAGE = 'demarrage'
EVENEMENT_BACKUP_SUCCES = 'succes'
EVENEMENT_BACKUP_ECHEC = 'echec'
EVENEMENT_BACKUP_MISEAJOUR = 'maj'
